[default]
DEBUG = ${DEBUG:-false}
SQLALCHEMY_DATABASE_URI = ${POSTGRES_URI}
MONGO_URI = ${MONGO_URI}
TITLE = "app"
SECRET_KEY = ${SECRET_KEY}
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
JWT_SECRET_KEY = ${JWT_SECRET_KEY}

EXTENSIONS = [
    "app.extensions.configuration:init_app",
    "app.extensions.sql_database:init_app",
    "app.extensions.nosql_database:init_app",
    "app.extensions.commands:init_app",
    "app.extensions.auth:init_app",
    "app.blueprints.api.v1:init_app"
]