[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres5432@localhost/pgavance'
MONGO_URI = 'mongodb://localhost:27017/mydb'
TITLE = "app"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']

EXTENSIONS = [
    "app.extensions.configuration:init_app",
    "app.extensions.sql_database:init_app",
    "app.extensions.nosql_database:init_app",
    "app.extensions.commands:init_app",
    "app.extensions.auth:init_app",
    "app.blueprints.api.v1:init_app"
]