name: Python application test with Github Actions

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      flask_db:
        image: postgres:17
        ports: ["5432:5432"]
        env:
          DB_URL: postgresql://postgres:postgres@flask_db:5432/postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: posgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        make install

    - name: Format code
      run: |
        make format

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      env:
        DB_URL: "postgresql://postgres:postgres@flask_db:5432/postgres
"
      run: |
        make test
